### ISSUE TITLE
MPI Smart Default for Processes per Host

### ISSUE THREAD

**Issue by canada4663** [aws/sagemaker-containers#203]
For the referenced line/section below, would it be reasonable to have a smart default here to consume all available GPU’s per host if executed inside SM job and the parameter isn’t supplied?

Would prevent user from having to translate p3.16xlarge to 8 GPU for instance, and modifying these parameters if changing instances.

https://github.com/aws/sagemaker-containers/blob/71bd1ce3da7a6c70c28736fd1b76303bbb8ed724/src/sagemaker_containers/_runner.py#L48

**Comment by ChoiByungWook** [comment]
@canada4663,

Apologies, as I am not an expert with MPI.

However, this seems like a reasonable proposal. How should this value be handled if a GPU isn't being used? Would it be safe to use the number of CPUs?

Let me reach out to the team and see what they think.

Thanks!

**Comment by armandmcqueen** [comment]
+1 for this idea. It's easy to implement since `sagemaker-containers` exposes the `SM_NUM_GPUS` environmental variable.

It seems like [1 process per host is a decent default when doing CPU training](https://github.com/horovod/horovod/issues/945#issuecomment-475917331). Also, I'm not sure if CPU training with Horovod is very common.

**Comment by ChoiByungWook** [comment]
Let me write a PR. I'll have the value of this variable follow this order:

1. customer input
2. env.num_gpus
3. 1

Whatever the customer defines as the value should override everything. If we detect GPUs we default to the number of them. Otherwise, we can assume the instance is CPU and we will default to 1.

**Comment by ChoiByungWook** [comment]
PR: https://github.com/aws/sagemaker-containers/pull/204

**Comment by ChoiByungWook** [comment]
While testing my image, it seems that the Python SDK defaults to 1 if one doesn't provide a value in the distributions in the constructor.

https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/tensorflow/estimator.py#L548

With this even if we do smart defaults it will go to 1.

**Comment by ChoiByungWook** [comment]
Python SDK PR to get around the default on the client side: https://github.com/aws/sagemaker-python-sdk/pull/928

**Comment by canada4663** [comment]
Great thanks!!!
